# ITP(Introduction To Programming)

In introduction to programming we learn about the python at zero level so lets start from scratch

#### Veriable

bsically Variable mencse a type of pokit there we store the data
}

In [1]:
x = 10 # Here x is the veriable

In [2]:
# lets check type of the veriable
type(x)

int

In [6]:
# In python there are number s of datatypes are present lets go and learn about all of them
y = 10.5
z = 10+90j
l = True
m = "Name"

In [7]:
type(y) # Float Datatypes

float

In [8]:
type(z) # Complex Datatype

complex

In [9]:
type(l)  # Boolean Datatype-

bool

In [10]:
type(m) # String Datatype

str

In [11]:
# Lets Check are we able to change the Datatype from one to other
int(y)

10

In [12]:
float(x)

10.0

In [14]:
int(z)

TypeError: can't convert complex to int

In [15]:
int(m)

ValueError: invalid literal for int() with base 10: 'Name'

In [16]:
n = "10"
int(n)

10

#### Inference
* Yes we can easity Convert the Datatype (float to integer and wise versa)
* But we cant convert the data in other Datatype like we wont convert the float or Int into comlex or bool
* Here we can able to convert the string into float or int but the condition was there need only number if there is name or other object present it wont convert

### List, Tuple, Set & Dictionary

In [1]:
list1 = [1,2,3,4]
type(list1) # List is basically a collection or sequence of objects, to identify the list see the list always have "[ ]" this type of brackets

list

In [2]:
tuple1 = (1,2,3,4)
type(tuple1) # It is the same as List just difference in brackets here in tuple we have "( )" or sometime no breckets are required

tuple

In [3]:
tuple2 = 1,2,3,4
type(list2)

tuple

In [14]:
set1 = {1,2,3}
type(list2) # Set is also collection on objects or list just difference in set is Breckets "{ }"

set

In [15]:
dict1 = {"Name":"Ram","Standered":7,"Section":"A","Study Medium":"English"}
type(dict1) # Here in Dictionary we have "KEY":"VALUE"

dict

#### Operation on this all

In [16]:
list1.append(75)

In [17]:
list1

[1, 2, 3, 4, 75, 75]

In [18]:
tuple1.append(75) # Not able to append

AttributeError: 'tuple' object has no attribute 'append'

In [19]:
set1.append(75) # Not able to append

AttributeError: 'set' object has no attribute 'append'

In [22]:
dict1.append({"School Name":"PCE"}) # Not able to append

AttributeError: 'dict' object has no attribute 'append'

In [30]:
list1.reverse()
list1

[75, 75, 4, 3, 2, 1]

In [31]:
list1.remove(75)
list1

[75, 4, 3, 2, 1]

In [33]:
list1.insert(0,88)
list1

[88, 75, 4, 3, 2, 1]

In [36]:
tuple1.count(1)

1

In [37]:
tuple1.index(3)

2

In [40]:
set1.add(76)
set1

{1, 2, 3, 76}

In [42]:
set1.clear()
set1

set()

In [47]:
dict1

{'Name': 'Ram', 'Standered': 7, 'Section': 'A', 'Study Medium': 'English'}

In [49]:
 dict1.keys()

dict_keys(['Name', 'Standered', 'Section', 'Study Medium'])

In [52]:
dict1.values()

dict_values(['Ram', 7, 'A', 'English'])

In [48]:
dict1["Name"]

'Ram'

In [50]:
dict1_copy = dict1.copy()
dict1_copy

{'Name': 'Ram', 'Standered': 7, 'Section': 'A', 'Study Medium': 'English'}

In [51]:
dict1.items()

dict_items([('Name', 'Ram'), ('Standered', 7), ('Section', 'A'), ('Study Medium', 'English')])

### Infarance
* List  "[ ]" is mutable that mense we can easily do changes in the same.
* Accordoing to operations we can say that excluding List we wont able to do changes in Tuple,Set,Dict
* So According to operations we can say that in tuple oinly we cannot change the data here we can only count and check the index of the data .
* In dictionary,list,tuple, set we can easily fetch the data by using index possitions.
* Keys and values are present in the Dictionary to change the data we have to give both Keys with Value

### Arrays
  Arrays are again the collection of the objects or say values arrays are sothing in ilnnear in nature and here we recognise by the dimension "[ ]" its looks like list and all operations as well that offers in the list do in arrays as well.

In [53]:
# Import the library
import numpy as np

In [55]:
# Create first 1D array
array1 = np.array([1,2,3,4,5,6])
array1
type(array1)

numpy.ndarray

In [57]:
# Create 2D array
array2 = np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
# 3D array
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [65]:
# Create array using "Range"
array4 = np.arange(1,11)
array4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# Create array that represent 2's table
array5 = np.arange(2,21,2) # "np.arange(start,stop,step)"
array5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
# Lets create arrat to matrix
sample_array = np.arange(2,21,2)
sample_array.reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [68]:
# Convert that data into matrix of 2*5
array5.reshape(2,5) # "array5.reshape(row,column)"

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [69]:
# Convert that data into matrix of 5*2
array5.reshape(5,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [73]:
# Do stacking on data
array11 = np.array([1,2,3,4,5,6])
array11
np.stack((array1,array11))

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [74]:
# Lets create Matrix
eye_mat = np.eye(3)
eye_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
eye_mat[eye_mat == 0] = 10
eye_mat[eye_mat == 1] = 1000
eye_mat

array([[1000.,   10.,   10.],
       [  10., 1000.,   10.],
       [  10.,   10., 1000.]])

In [82]:
# Lets Create matrix using Random function
mat1 = np.random.rand(3,3) # "np.random.rand(Row,Column)"
mat1

array([[0.37736914, 0.32159986, 0.8803997 ],
       [0.04021693, 0.8482476 , 0.37225698],
       [0.608398  , 0.08337181, 0.35637452]])

In [100]:
mat2 = np.random.rand(2,3,3) # np.random.rand(no of matrixes,Rows,Column)
mat2

array([[[0.11659105, 0.02965493, 0.52572205],
        [0.81745505, 0.27009597, 0.24256862],
        [0.93971327, 0.99403579, 0.41148791]],

       [[0.8580779 , 0.32003274, 0.41190782],
        [0.27217917, 0.74492478, 0.65175133],
        [0.50405141, 0.73449429, 0.44706839]]])

#### Operations on arrays & Matrics

In [83]:
mat1.sum() # Sumession

3.8882345493783186

In [84]:
mat1.std() # Standeres Deviation

0.279868493532656

In [86]:
mat1.var() # Veriance

0.07832637367223833

In [87]:
mat1.mean() # Avearge of matrix

0.4320260610420354

In [88]:
mat1.max()  # Maxima

0.8803997047262382

In [89]:
mat1.min() # Minima

0.040216929710828575

In [102]:
# Change the data in array
array6 = np.arange(2,21,2)
array6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
array6[0:4] = 7
array6

array([ 7,  7,  7,  7, 10, 12, 14, 16, 18, 20])

In [105]:
# Fetch the data using index Possitions
mat1

array([[0.37736914, 0.32159986, 0.8803997 ],
       [0.04021693, 0.8482476 , 0.37225698],
       [0.608398  , 0.08337181, 0.35637452]])

In [106]:
mat1[1,2]

0.37225697700075644

In [107]:
mat1[0,0]

0.3773691445923406

In [111]:
# Etract whole Column
mat1[:,1]

array([0.32159986, 0.8482476 , 0.08337181])

In [110]:
# Extract whole Row
mat1[1,:]

array([0.04021693, 0.8482476 , 0.37225698])

### Infarance
* arrays are somthing that store the data in stack minor.
* Arrays formes in dimensions like 1D array,2D array 3Darray that meaning the data store in multidimensions.
* Here in Matrixs we are able to do mathmatical operations as well 

### Dataframe

In [112]:
import pandas as pd # Pandas basically use to structer the data according to our requirement

In [113]:
# Creat a simple Dataframe
df1 = pd.DataFrame(data = (np.random.randn(10,5)),index = 'a b c d e f g h i j'.split(),columns = 'col1 col2 col3 col4 col5'.split())
df1

col1      col2      col3      col4      col5
a  0.753501  0.166237  1.023471  0.888574  0.826835
b  0.115859 -0.316772  0.549966  0.419034  0.289707
c  2.040217  1.310418  0.153814  0.766725  0.980693
d -2.716806 -0.402971 -0.143048 -1.829044  1.621947
e  0.649320 -0.496229  0.846343 -0.514220 -0.364005
f  0.819802  0.497211 -1.119519 -1.093763 -0.644699
g -0.694226 -0.304642  0.967920 -1.398846  0.326957
h -0.152550  0.131603  0.209498 -0.578436 -1.907686
i  2.190778 -0.188546  0.722312  1.144743  1.260159
j -0.856005  0.474112  0.703230  1.243243 -0.885694

In [119]:
# Set Index
new_index = 'jap ind usa aus can jer pak ban afr eng'.split() # Create new column on the name as new index
df1['Countries'] = new_index # Set that new index in the dataframe as column
df1.set_index('Countries',inplace = True) # Now assign that column as Index
df1

col1      col2      col3      col4      col5
Countries                                                  
jap        0.753501  0.166237  1.023471  0.888574  0.826835
ind        0.115859 -0.316772  0.549966  0.419034  0.289707
usa        2.040217  1.310418  0.153814  0.766725  0.980693
aus       -2.716806 -0.402971 -0.143048 -1.829044  1.621947
can        0.649320 -0.496229  0.846343 -0.514220 -0.364005
jer        0.819802  0.497211 -1.119519 -1.093763 -0.644699
pak       -0.694226 -0.304642  0.967920 -1.398846  0.326957
ban       -0.152550  0.131603  0.209498 -0.578436 -1.907686
afr        2.190778 -0.188546  0.722312  1.144743  1.260159
eng       -0.856005  0.474112  0.703230  1.243243 -0.885694

In [127]:
df2 = pd.DataFrame(data = (np.random.randn(10,5)),index = 'a b c d e f g h i j'.split(),columns = 'col6 col7 col8 col9 col10'.split())
df2

col6      col7      col8      col9     col10
a -1.213590  0.326945  0.673658 -0.810158  0.046336
b  0.149757 -0.775584 -0.359934  0.925013  0.165166
c -1.680386 -0.344306 -0.953017 -1.314965 -1.484993
d -0.092289  0.547112  0.027790  0.126754 -0.307009
e  0.726808  2.721445  1.169916 -1.292283 -1.405422
f  0.867912 -0.266256  1.020380  0.309732 -1.125676
g -0.225420 -0.207998  0.988278 -1.199536 -0.677970
h -1.744461 -1.015323  0.871724 -0.113583  0.293255
i -0.977388 -1.327915  0.615439 -0.533513  0.758304
j -0.724736 -0.078810  0.136556  0.054989 -1.113295

In [138]:
# Handle the NaN values
df3 = pd.DataFrame({"Name":["Ram","Sham","Vishal","Sachin","Nikhil","Prajwal"]
                    ,"Science":[50,67,88,75,88,np.nan],"Maths":[66,87,98,np.nan,76,56],
                    "English":[91,77,98,np.nan,76,84]})
df3

Name  Science  Maths  English
0      Ram     50.0   66.0     91.0
1     Sham     67.0   87.0     77.0
2   Vishal     88.0   98.0     98.0
3   Sachin     75.0    NaN      NaN
4   Nikhil     88.0   76.0     76.0
5  Prajwal      NaN   56.0     84.0

In [144]:
#  Drop all Na values
df3.dropna()

Name  Science  Maths  English
0     Ram     50.0   66.0     91.0
1    Sham     67.0   87.0     77.0
2  Vishal     88.0   98.0     98.0
4  Nikhil     88.0   76.0     76.0

In [146]:
# Fill Nan with median
df3.fillna(df3.median())

Name  Science  Maths  English
0      Ram     50.0   66.0     91.0
1     Sham     67.0   87.0     77.0
2   Vishal     88.0   98.0     98.0
3   Sachin     75.0   76.0     84.0
4   Nikhil     88.0   76.0     76.0
5  Prajwal     75.0   56.0     84.0

In [148]:
df4 = pd.DataFrame({"Name":["Ram","Sham","Vishal","Sachin","Nikhil","Prajwal","Ram","Sham","Vishal","Sachin","Nikhil","Prajwal"]
                    ,"Science":[50,67,88,75,88,np.nan,50,67,88,75,88,np.nan],"Maths":[66,87,98,np.nan,76,56,66,87,98,np.nan,76,56],
                    "English":[91,77,98,np.nan,76,84,91,77,98,np.nan,76,84]})
df4

Name  Science  Maths  English
0       Ram     50.0   66.0     91.0
1      Sham     67.0   87.0     77.0
2    Vishal     88.0   98.0     98.0
3    Sachin     75.0    NaN      NaN
4    Nikhil     88.0   76.0     76.0
5   Prajwal      NaN   56.0     84.0
6       Ram     50.0   66.0     91.0
7      Sham     67.0   87.0     77.0
8    Vishal     88.0   98.0     98.0
9    Sachin     75.0    NaN      NaN
10   Nikhil     88.0   76.0     76.0
11  Prajwal      NaN   56.0     84.0

In [150]:
# Use Groupby Function
df4.groupby('Name').mean()

Science  Maths  English
Name                            
Nikhil      88.0   76.0     76.0
Prajwal      NaN   56.0     84.0
Ram         50.0   66.0     91.0
Sachin      75.0    NaN      NaN
Sham        67.0   87.0     77.0
Vishal      88.0   98.0     98.0

In [151]:
# Details of the Dataframe 
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
Name       12 non-null object
Science    10 non-null float64
Maths      10 non-null float64
English    10 non-null float64
dtypes: float64(3), object(1)
memory usage: 512.0+ bytes


In [152]:
# Describe the Dataframe\
df4.describe()

Science      Maths    English
count  10.000000  10.000000  10.000000
mean   73.600000  76.600000  85.200000
std    15.034775  15.657444   8.829244
min    50.000000  56.000000  76.000000
25%    67.000000  66.000000  77.000000
50%    75.000000  76.000000  84.000000
75%    88.000000  87.000000  91.000000
max    88.000000  98.000000  98.000000

In [162]:
df_concatinated = pd.concat([df2,df3],sort=False) 
df_concatinated

col6      col7      col8      col9     col10     Name  Science  Maths  \
a -1.213590  0.326945  0.673658 -0.810158  0.046336      NaN      NaN    NaN   
b  0.149757 -0.775584 -0.359934  0.925013  0.165166      NaN      NaN    NaN   
c -1.680386 -0.344306 -0.953017 -1.314965 -1.484993      NaN      NaN    NaN   
d -0.092289  0.547112  0.027790  0.126754 -0.307009      NaN      NaN    NaN   
e  0.726808  2.721445  1.169916 -1.292283 -1.405422      NaN      NaN    NaN   
f  0.867912 -0.266256  1.020380  0.309732 -1.125676      NaN      NaN    NaN   
g -0.225420 -0.207998  0.988278 -1.199536 -0.677970      NaN      NaN    NaN   
h -1.744461 -1.015323  0.871724 -0.113583  0.293255      NaN      NaN    NaN   
i -0.977388 -1.327915  0.615439 -0.533513  0.758304      NaN      NaN    NaN   
j -0.724736 -0.078810  0.136556  0.054989 -1.113295      NaN      NaN    NaN   
0       NaN       NaN       NaN       NaN       NaN      Ram     50.0   66.0   
1       NaN       NaN       NaN       NaN       NaN     Sham     67.0   87.0   
2       NaN       NaN       NaN       NaN       NaN   Vishal     88.0   98.0   
3       NaN       NaN       NaN       NaN       NaN   Sachin     75.0    NaN   
4       NaN       NaN       NaN       NaN       NaN   Nikhil     88.0   76.0   
5       NaN       NaN       NaN       NaN       NaN  Prajwal      NaN   56.0   

   English  
a      NaN  
b      NaN  
c      NaN  
d      NaN  
e      NaN  
f      NaN  
g      NaN  
h      NaN  
i      NaN  
j      NaN  
0     91.0  
1     77.0  
2     98.0  
3      NaN  
4     76.0  
5     84.0

In [163]:
df_concatinated.fillna(0)

col6      col7      col8      col9     col10     Name  Science  Maths  \
a -1.213590  0.326945  0.673658 -0.810158  0.046336        0      0.0    0.0   
b  0.149757 -0.775584 -0.359934  0.925013  0.165166        0      0.0    0.0   
c -1.680386 -0.344306 -0.953017 -1.314965 -1.484993        0      0.0    0.0   
d -0.092289  0.547112  0.027790  0.126754 -0.307009        0      0.0    0.0   
e  0.726808  2.721445  1.169916 -1.292283 -1.405422        0      0.0    0.0   
f  0.867912 -0.266256  1.020380  0.309732 -1.125676        0      0.0    0.0   
g -0.225420 -0.207998  0.988278 -1.199536 -0.677970        0      0.0    0.0   
h -1.744461 -1.015323  0.871724 -0.113583  0.293255        0      0.0    0.0   
i -0.977388 -1.327915  0.615439 -0.533513  0.758304        0      0.0    0.0   
j -0.724736 -0.078810  0.136556  0.054989 -1.113295        0      0.0    0.0   
0  0.000000  0.000000  0.000000  0.000000  0.000000      Ram     50.0   66.0   
1  0.000000  0.000000  0.000000  0.000000  0.000000     Sham     67.0   87.0   
2  0.000000  0.000000  0.000000  0.000000  0.000000   Vishal     88.0   98.0   
3  0.000000  0.000000  0.000000  0.000000  0.000000   Sachin     75.0    0.0   
4  0.000000  0.000000  0.000000  0.000000  0.000000   Nikhil     88.0   76.0   
5  0.000000  0.000000  0.000000  0.000000  0.000000  Prajwal      0.0   56.0   

   English  
a      0.0  
b      0.0  
c      0.0  
d      0.0  
e      0.0  
f      0.0  
g      0.0  
h      0.0  
i      0.0  
j      0.0  
0     91.0  
1     77.0  
2     98.0  
3      0.0  
4     76.0  
5     84.0

In [164]:
np.save('Concatinate_Data.npy',df_concatinated) # Save Single dataframe

In [167]:
np.savez('All_dataframes.npz',a = df1,b = df2,c = df3,d = df4) # save Multiple dataframe

In [170]:
np.load('Concatinate_Data.npy')

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [171]:
x = np.load('All_dataframes.npz')

In [176]:
x["c"]

ValueError: Object arrays cannot be loaded when allow_pickle=False